name: Check commit
on:
  push:
    branches: [main, release]
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - run: yarn install
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
      - run: yarn monorepo
      - run: yarn update:deps

      - name: Commit nzyme updates
        run: |
          if git diff --exit-code; then
            echo "No changes to commit."
          else
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"
            git commit -a -m "chore: update nzyme packages"
            git push
          fi

      - run: yarn build
      # - run: yarn test
      - run: yarn smoke
